
// WhiteListAlerts handles which alerts will be shown to the user
export const WhiteListAlerts = [
  "CASE_UPDATE",
  "CASE_CONFIG_GET_ESTIMATE_AJAX_TRIO",
  "CASE_DELETE_COLLECTOR_AJAX_TRIO",
  "LOGOUT_OF_FATC_AJAX_TRIO",
  "CASE_RUN_COLLECTOR_SERIES_AJAX_TRIO",
  "UPDATE_USER_AJAX_TRIO",
  "UPDATE_USER_PASSWORD_AJAX_TRIO",
  "ADD_NEW_USER_AJAX_TRIO",
  "CHECK_USER_AUTH_AJAX_TRIO",
  "LOGIN_TO_FATC_AJAX_TRIO",
  "UPDATE_USER_SELF_PASSWORD_AJAX_TRIO",
  "CASE_CREATE_BY_ID_AJAX_TRIO"
]
